name: Feature request
description: Request an enhancement
type: Feature
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the requested feature.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    attributes:
      label: "Problem"
      description: "Describe the problem to be solved. Include references to other projects if relevant."
      placeholder: "Option is not implemented. Option is useful because ..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Expected behavior"
      description: "Describe what the new feature or behavior would look like. How does it solve the problem? Is it worth the cost?"
    validations:
      required: true
